version: '3'
services:
  mysql_first:
      image: mysql:5.7
      restart: always
      environment:
        MYSQL_ROOT_PASSWORD: $SQL_PASSWORD
      ports:
        - 3307:3306
      volumes:
        - mysql:/var/lib/mysql
volumes:
  mysql: